### ISSUE TITLE
ValueError: bad marshal data (unknown type code)

### ISSUE THREAD

**Issue by Gs0000** [SeanNaren/warp-ctc#117]
Traceback (most recent call last):
  File "setup.py", line 64, in <module>
    cmdclass={'build_ext': BuildExtension}
  File "/home/goooo/anaconda3/envs/pytorch/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/home/goooo/anaconda3/envs/pytorch/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/goooo/anaconda3/envs/pytorch/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/goooo/anaconda3/envs/pytorch/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/goooo/anaconda3/envs/pytorch/lib/python3.6/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/goooo/anaconda3/envs/pytorch/lib/python3.6/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/goooo/anaconda3/envs/pytorch/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/goooo/anaconda3/envs/pytorch/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/goooo/anaconda3/envs/pytorch/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 220, in run
    os.path.join(archive_root, 'EGG-INFO'), self.zip_safe()
  File "/home/goooo/anaconda3/envs/pytorch/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 273, in zip_safe
    return analyze_egg(self.bdist_dir, self.stubs)
  File "/home/goooo/anaconda3/envs/pytorch/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 383, in analyze_egg
    safe = scan_module(egg_dir, base, name, stubs) and safe
  File "/home/goooo/anaconda3/envs/pytorch/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 422, in scan_module
    code = marshal.load(f)
ValueError: bad marshal data (unknown type code)

**Comment by Gs0000** [comment]
solved

**Comment by tim120526** [comment]
> solved

HI,can you tell me how to solve it ?

**Comment by 1ucayu** [comment]
> 
I also solved. Check the version of setuptools.
I failed because the older version (19.2).
