### ISSUE TITLE
AttributeError: type object '_CTC' has no attribute 'apply'

### ISSUE THREAD

**Issue by vivounicorn** [SeanNaren/warp-ctc#22]
hi @SeanNaren, there is something wrong with CTCLoss of pytorch binding:
>>> import torch
>>> from torch.autograd import Variable
>>> from warpctc_pytorch import CTCLoss
>>> ctc_loss = CTCLoss()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/anaconda2/envs/chinese-ocr/lib/python2.7/site-packages/warpctc_pytorch/__init__.py", line 55, in __init__
    self.ctc = _CTC.apply
AttributeError: type object '_CTC' has no attribute 'apply'
is there some way to solve it?

**Comment by vivounicorn** [comment]
May be the version of pytorch is too low.

**Comment by LMig2k** [comment]
i have the same problem on pytorch 0.1.12

**Comment by SeanNaren** [comment]
@vivounicorn what version you using? @LMig2k I'd suggest updating the pytorch version if possible

**Comment by zxczhkzxc** [comment]
i meet this problem,do you fix it?@LMig2k@vivounicorn

**Comment by w7851435** [comment]
i meet the same error..

**Comment by zxczhkzxc** [comment]
i try to update the version of pytorch and  solve the problem

**Comment by gbolin** [comment]
Do not use pytorch 0.1.12, its _CTC function does not have attribute apply.
here is the proof.
vim warp-ctc/pytorch_binding/warpctc_pytorch/__init__.py +60
we know that 'apply' from _CTC function, and the _CTC inherits the Function
in __init__.py row 3, the Function imported from torch.autograd.
ok, track the torch source code from the [website](http://pytorch.org/docs/0.1.12/_modules/torch/autograd/function.html#Function)
the Function surely does not have apply attribute, 
we can get a compare result form pytorch [0.2.0](http://pytorch.org/docs/0.2.0/_modules/torch/autograd/function.html#Function) or [0.3.1](http://pytorch.org/docs/0.3.1/_modules/torch/autograd/function.html#Function)
so I guess it's a bug here, use a higher version pytorch instead
