### ISSUE TITLE
ImportError....undefined symbol

### ISSUE THREAD

**Issue by toddlt** [SeanNaren/warp-ctc#24]
after `python setup.py install`, I run test.py, and get this:
```
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    from warpctc_pytorch import CTCLoss
  File "/usr/local/lib/python3.4/dist-packages/warpctc_pytorch/__init__.py", line 8, in <module>
    from ._warp_ctc import lib as _lib, ffi as _ffi
ImportError: /usr/local/lib/python3.4/dist-packages/warpctc_pytorch/_warp_ctc.cpython-34m.so: undefined symbol: _Z7cpu_ctcP13THFloatTensorS0_P11THIntTensorS2_S2_iS0_
```
It doesn't support python3.4 ?

**Comment by 1711120070** [comment]
same error.
DO YOU KNEW HOW TO SOLVE?

**Comment by wgharbieh** [comment]
@toddlt Did you try installing it using python 3.6?
