### ISSUE TITLE
problem installing warpctc

### ISSUE THREAD

**Issue by gulzainali98** [SeanNaren/warp-ctc#28]
/usr/bin/ld: cannot find -lluajit
/usr/bin/ld: cannot find -lTHC
collect2: error: ld returned 1 exit status
CMakeFiles/warpctc.dir/build.make:702: recipe for target 'libwarpctc.so' failed
make[2]: *** [libwarpctc.so] Error 1
CMakeFiles/Makefile2:178: recipe for target 'CMakeFiles/warpctc.dir/all' failed
make[1]: *** [CMakeFiles/warpctc.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by BigBorg** [comment]
I'm able to compile and install without error. But the tests fail. Traceback as follows:

```
Traceback (most recent call last):
  File "test.py", line 59, in test_simple
    cpu_cost, cpu_grad = self._run_grads(label_sizes, labels, probs, sizes)
  File "test.py", line 22, in _run_grads
    cost = ctc_loss(probs, labels, sizes, label_sizes)
  File "/home/borg/anaconda2/envs/neural/lib/python3.6/site-packages/torch/nn/modules/module.py", line 363, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/borg/anaconda2/envs/neural/lib/python3.6/site-packages/warpctc_pytorch-0.1-py3.6-linux-x86_64.egg/warpctc_pytorch/__init__.py", line 76, in forward
    self.length_average)
  File "/home/borg/anaconda2/envs/neural/lib/python3.6/site-packages/warpctc_pytorch-0.1-py3.6-linux-x86_64.egg/warpctc_pytorch/__init__.py", line 17, in forward
    loss_func = warp_ctc.gpu_ctc if is_cuda else warp_ctc.cpu_ctc
AttributeError: module 'warpctc_pytorch' has no attribute 'cpu_ctc'
```

**Comment by sdzbft** [comment]
i am facing the same problem,,Can you tell me how do you solve that?  thx

**Comment by MNCTTY** [comment]
Me too. Have you found any solution?
