### ISSUE TITLE
Data Parallel not supported

### ISSUE THREAD

**Issue by hyichao** [SeanNaren/warp-ctc#78]
Hi,

While using CTCLoss as a submodule in  pytorch, I found that CTCLoss cannot work with multi GPU. 

The reason is that `torch.nn.DataParallel` ensures all submodules will be under parallel mode, and the input of forward function should be all `torch.Tensor` and the dim of input tensor should be at least 2, since data parallel will split the tensor by dim 0. 

However,  the input(2,3,4) of `CTCLoss forward` should be 1-dimensional according to [README](https://github.com/SeanNaren/warp-ctc/blob/pytorch_bindings/README.md).

The case of CTCLoss as a submodule of another `nn.Module`

```
class Network(nn.Module):
    ...
    def __init__(self):
        self.criterion = CTCLoss()
```

I've print the tensor size before calling `CTCLoss.foward()`
```
data size before warp ctc
torch.Size([82, 16, 34]) torch.Size([35]) torch.Size([16]) torch.Size([16]) 
```

The error shows like the following

```
data size before warp ctc
torch.Size([82, 16, 34]) torch.Size([35]) torch.Size([16]) torch.Size([16]) 
Traceback (most recent call last):
  File "train.py", line 473, in <module>
    train()
  File "train.py", line 300, in train
    target_det=target_det, target_ctc=target_ctc, target_sizes=target_sizes)
  File "/home/charlie_huang/virtual3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/charlie_huang/virtual3/lib/python3.5/site-packages/torch/nn/parallel/data_parallel.py", line 115, in forward
    return self.gather(outputs, self.output_device)
  File "/home/charlie_huang/virtual3/lib/python3.5/site-packages/torch/nn/parallel/data_parallel.py", line 127, in gather
    return gather(outputs, output_device, dim=self.dim)
  File "/home/charlie_huang/virtual3/lib/python3.5/site-packages/torch/nn/parallel/scatter_gather.py", line 68, in gather
    return gather_map(outputs)
  File "/home/charlie_huang/virtual3/lib/python3.5/site-packages/torch/nn/parallel/scatter_gather.py", line 63, in gather_map
    return type(out)(map(gather_map, zip(*outputs)))
  File "/home/charlie_huang/virtual3/lib/python3.5/site-packages/torch/nn/parallel/scatter_gather.py", line 55, in gather_map
    return Gather.apply(target_device, dim, *outputs)
  File "/home/charlie_huang/virtual3/lib/python3.5/site-packages/torch/nn/parallel/_functions.py", line 54, in forward
    ctx.input_sizes = tuple(map(lambda i: i.size(ctx.dim), inputs))
  File "/home/charlie_huang/virtual3/lib/python3.5/site-packages/torch/nn/parallel/_functions.py", line 54, in <lambda>
    ctx.input_sizes = tuple(map(lambda i: i.size(ctx.dim), inputs))
RuntimeError: dimension specified as 0 but tensor has no dimensions

```

Any idea to fix this? 
Many Thanks.

**Comment by hyichao** [comment]
1. Use `unsqueeze(0)` to make those 1-dim input tensor into 2-dim
2. Remove the `assert len(labels.size()) == 1` in `warp-ctc/pytorch_binding/warpctc_pytorch/__init__.py`
3. Rerun `python setup.py install`
Seems to solve the problem. I'll closed this issue.
