### ISSUE TITLE
ImportError: cannot import name '_assert_no_grad'

### ISSUE THREAD

**Issue by gbolin** [SeanNaren/warp-ctc#96]
hello friends, I met the following problem:
"from warpctc_pytorch import CTCLoss"
get a error:

> Traceback (most recent call last):
  File "crnn_new.py", line 20, in <module>
    from warpctc_pytorch import CTCLoss
  File "/usr/local/lib/python3.5/site-packages/warpctc_pytorch-0.1-py3.5-linux-x86_64.egg/warpctc_pytorch/__init__.py", line 6, in <module>
    from torch.nn.modules.loss import _assert_no_grad
ImportError: cannot import name '_assert_no_grad'

my pytorch version 0.4.1, but 0.4.0 works well.
so it relates to the pytorch version ?

**Comment by SeanNaren** [comment]
Try using https://github.com/SeanNaren/warp-ctc/tree/0.4.1

**Comment by mohamad-hasan-sohan-ajini** [comment]
Hello @SeanNaren 

I get the same error installing warp-ctc from current master branch:

> aj@aj-pc:~/repo/warp-ctc/pytorch_binding/tests$ python test_gpu.py 
Traceback (most recent call last):
  File "test_gpu.py", line 2, in <module>
    import warpctc_pytorch as warp_ctc
  File "/usr/local/lib/python3.5/dist-packages/warpctc_pytorch/__init__.py", line 6, in <module>
    from torch.nn.modules.loss import _assert_no_grad
ImportError: cannot import name '_assert_no_grad'

I think merging jinserk pull request will solve issues with pytorch1.0, but it's not!
